### ISSUE TITLE
Persistencia de datos de revisiones

### ISSUE THREAD

**Issue by mjuez** [mjuez/TFM2016_Analisis-Visual-Revisiones-Codigo#13]
Tenemos que buscar una solución para gestionar la persistencia de los datos obtenidos de la API de Github para tratar de minimizar el número de peticiones necesarias a dicha API.

Dependiendo del tipo de sistema gestor de persistencia que escojamos (SQL, NoSQL, ficheros) existen diversas herramientas (ORM, ODM) para NodeJS que podrían facilitarnos el manejo de los datos.

NoSQL ODM (mongodb)

- [Mongoose](http://mongoosejs.com/)
- [Mongorito](http://mongorito.com/)

SQL ORM (PostgreSQL, MySQL, MariaDB...) 

- [Sequelize](http://docs.sequelizejs.com/en/v3/)

Como opción adicional existe [ToroDB](https://www.8kdata.com/es/torodb), un tipo de base de datos que es una mezcla entre NoSQL y SQL. Las consultas se hacen con la sintaxis de mongodb y los datos son almacenados en una base de datos PostgreSQL.

**Comment by clopezno** [comment]
Estoy dirigiendo un TFM a Mario Juez (le pongo en  copia)  que accede a los datos de las revisiones de código disponibles en Github y nos han surgido un par de dudas.

    ¿Hay alguna forma de superar la 5000 peticiones por hora al API de Github?
    ¿El diseño arquitectónico  de la aplicación debería almacenar los datos en bases de datos Nosql (MongoDB) tal como  escribimos en [ERCIM News No. 99 - Special Theme: "Software Quality" Mining Open Software Repository](https://ercim-news.ercim.eu/en99/special/mining-open-software-repositories)  o aconsejas otro? Inicialmente queríamos acceder con Node.js.


Sobre la restricción de peticiones por hora, me temo que no, salvo que haya cambiado desde la última vez (que no creo). La restricción por defecto es de 60 peticiones, y si es para aplicaciones registradas (deberían darte un token de aplicación o alguna otra forma de saber "quien" eres), es de 5000. Imagino que ese límite está hecho para evitar que se colapsen sus servidores con peticiones de downloaders como GHTorrent. Recuerda que cuando se solicitaba a GHTorrent que descargase los datos de un proyecto, podía tardar entre varias horas a varios días, según el tamaño del proyecto. Imagino que por esta razón.

Sobre el SGBD, pues dependerá del uso que quieras hacer de los datos y lo que te quieras complicar. NoSQL está pensado para acceder a los datos en tiempo real; es más un almacén de datos que una base de datos. La principal ventaja que veo a MongoDB en este caso es que a) es inmediato volcar las colecciones desde GitHub a una BD Mongo, y b) que los datos están ya en formato JSON y desde NodeJS te vienen ya estructurados y sólo es leerlos. La desventaja: Principalmente que no tienes posibilidad de hacer operaciones complejas en las consultas (ordenar, filtrar, limitar y poco más); tal vez algún join sencillo se pueda hacer, pero casi sale mejor hacerlo a mano desde JavaScript una vez leídas las tablas. Si más que la inmediatez para disponer de los datos te interesa cruzarlos, una base de datos relacional como MySQL u Oracle seguramente sea lo más indicado. Lo primero que necesitarías es un adaptador para poder conectar NodeJS con la base de datos (o montar una interfaz rest o similar para rellenar la BD con los datos obtenidos desde GitHub). Una vez que lo tengas, tendrías que transformar los datos recibidos al SGBD relacional que hayas elegido. Para eso ten en cuenta que, por la dificultad de cruzar tablas y la importancia de la disponibilidad vs la flexibilidad, en las BDs NoSQL muchos de los datos van duplicados (si no recuerdo mal, parte de los datos de los autores venían en otras tablas). Esto es crucial en este punto, porque el duplicado de esos datos es parcial (es decir, en un commit te vienen los datos del autor y el committer importantes para el commit, pero los datos completos del usuario no van ahí); aquí hay que identificar qué tablas dependen de cuáles, y comenzar por las que no tienen dependencias, ya que si no al intentar insertar las FKs dará un error por no existir las entradas relacionadas.

Personalmente empezaría por almacenar el volcado en MongoDB para tenerlo disponible. Luego, decidiría si me saldría rentable transformarlo a una BD relacional:

    ¿Tendría que transformar todas las tablas o sólo algunas? Si sólo son algunas, la transformación podría ser sencilla.
    ¿Tendría que hacer muchas consultas complejas diferentes con uno o varios join? Según la consulta, hacerla manipulando los datos en JavaScript podría ser más sencillo que transformar los datos e insertarlos en la BD, pero cada consulta se hace "artesanalmente", luego si van a ser unas cuantas, definitivamente será más cómodo y rentable hacerlas en SQL.

**Comment by mjuez** [comment]
Por mi parte veo bien seguir la recomendación de @kencho y empezar utilizando MongoDB, aunque creo que no necesitamos toda la información obtenida de cada llamada a la API de github, inicialmente sí que podríamos empezar guardando todo y más adelante cuando tenga más conocimiento sobre el problema y como lo queremos resolver, decidir qué datos nos interesan y cuales no.

Ahora mismo, entiendo que en nuestro proyecto no deberíamos hacer consultas muy complejas, pero posiblemente en el siguiente proyecto, donde se va a intentar extraer conocimiento de nuestros datos sí, así que a lo mejor pensando en el uso futuro sí que podría ser más interesante una BBDD relacional.

**Comment by mjuez** [comment]
Acabo de encontrar este proyecto de Microsoft (nace en Octubre de 2016) [GHCrawler](https://github.com/Microsoft/ghcrawler).

No estoy seguro, pero creo que es una herramienta para extraer datos de repositorios a través de la API de Github tratando de optimizar el número de llamadas.

Dice que está preparado para trabajar con bases de datos como [Microsoft Azure Blob](https://azure.microsoft.com/en-us/services/storage/blobs/) o MongoDB.

**Comment by Kencho** [comment]
En el Readme de GHCrawler comentan esto (énfasis añadido por mí):

> [...] It makes heavy use of etags, Redis, client-side rate limiting, and **GitHub token pooling and rotation to optimize use of your API tokens** and not beat up the GitHub API.

Por lo que he podido ver, GHCrawler permite utilizar varios tokens del API simultáneamente para "saltarse" la limitación de 5000 consultas por hora. Cuidado con esto, porque probablemente entre directamente en conflicto con el punto G.2 de los [términos de uso de GitHub](https://help.github.com/articles/github-terms-of-service/#g-api-terms):

> Abuse or excessively frequent requests to GitHub via the API may result in the temporary or permanent suspension of your account's access to the API. GitHub, in our sole discretion, will determine abuse or excessive usage of the API. We will make a reasonable attempt to warn you via email prior to suspension.
> 
> You may not share API tokens to exceed GitHub's rate limitations. [...]

Si bien es cierto que no es obligatorio hacer uso de varios tokens, GHCrawler ofrece la posibilidad y es tentador hacerlo. Eso sí, aunque GitHub no acabase detectándolo, podría seguir siendo un uso ilícito del servicio que iría en contra de la ética profesional. Creo que es importante mencionar esto.

Salvo por ese detalle, haciendo un uso ético del API (i.e., usando sólo un token), podría ser una herramienta muy interesante para el volcado de los datos.

**Comment by mjuez** [comment]
En la reunión de hoy hemos decidido utilizar MongoDB finalmente.
