### ISSUE TITLE
Prototipo para probar persistencia con MongoDB

### ISSUE THREAD

**Issue by mjuez** [mjuez/TFM2016_Analisis-Visual-Revisiones-Codigo#16]
Este prototipo tiene como fin obtener por ejemplo una Pull Request de un repositorio GitHub y almacenarla localmente en una base de datos MongoDB.

Al parecer Heroku permite la instalación de MongoDB a través de un addon llamado [mLab MongoDB](https://elements.heroku.com/addons/mongolab), pero la versión gratuita está limitada a 496mb, por ello se trabajará con dos bases de datos, una local y la de heroku, se debería buscar la forma de que al realizar el despliegue (usando travis), se modifique la cadena de conexión para utilizar la base de datos de heroku en lugar de la local, en otras palabras, entorno de desarrollo (local) y entorno de producción (remoto)

**Comment by clopezno** [comment]
En el [siguiente artículo](http://www.gousios.gr/pub/pullreqs-dataset.pdf) se seleccionan las características de un pullrequest. Los criterios de clasificación de alto nivel son:

- Características del pull request - 16 medidas
- Características del proyecto - 8 medidas
- Características del desarrollador - 3 medidas


El análisis de datos esta hecho con R y obtenidos con [GHTorrent](http://ghtorrent.org/downloads.html)

**Comment by mjuez** [comment]
No me ha sido posible terminar con el prototipo a tiempo antes del final del sprint. Las tareas de documentación me han llevado más tiempo de lo que esperaba.
