### ISSUE TITLE
Correcciones y mejora de conceptos teóricos

### ISSUE THREAD

**Issue by mjuez** [mjuez/TFM2016_Analisis-Visual-Revisiones-Codigo#19]
Se debe incluir el diagrama de #5 en la sección de conceptos teóricos como justificación y base de nuevos conceptos a definir. También se debe revisar la sección y corregir erratas.

**Comment by clopezno** [comment]
Sustituir el concepto de requerimiento por etiqueta/label en el diagrama conceptula. Se puede incluir los tipos de etiquetas que proporciona Github por defecto.
