### ISSUE TITLE
Aprendizaje del uso de la plantilla de Latex para la documentación

### ISSUE THREAD

**Issue by clopezno** [mjuez/TFM2016_Analisis-Visual-Revisiones-Codigo#2]
En el repositorio he cargado en la carpeta memoLatex la plantilla que se utiliza en el TFG de GII. Se necesita ajustar sustituyendo todas las referencias de "TFG o Trabajo Fin de Grado" por "TFM o Trabajo Fin de Máster"

La herramienta que aconsejo utilizar para compilar LateX es [TexMaker](http://www.xm1math.net/texmaker/)

**Comment by clopezno** [comment]
Nueva cersión en este [repositorio ](https://github.com/ubutfgm/plantillaLatex)

**Comment by mjuez** [comment]
He empezado a definir los conceptos teóricos utilizando la plantilla LaTeX. Su uso está muy bien documentado y no he tenido problemas.
