### ISSUE TITLE
Gestión de cola de peticiones a la API de Github

### ISSUE THREAD

**Issue by mjuez** [mjuez/TFM2016_Analisis-Visual-Revisiones-Codigo#27]
Mejorar el prototipo implementando un sistema de colas para tratar el límite de 5000 peticiones a la API de Github. Cuando se terminan las peticiones, se debe recordar el progreso de la tarea actual y continuarlo en el momento de renovación del límite de peticiones.

**Comment by mjuez** [comment]
No me va a ser posible terminar esta tarea en éste sprint por una mala estimación de tiempos.

**Comment by clopezno** [comment]
Desde mi punto de vista no ha sido _una mala estimación de tiempos_. Las tareas de este sprint tenían mucha incertidumbre y por no tener una definición precisa, esa ha sido la razón funadamental de la desviación de tiempos.
