### ISSUE TITLE
Conceptos teóricos sobre revisiones de código

### ISSUE THREAD

**Issue by clopezno** [mjuez/TFM2016_Analisis-Visual-Revisiones-Codigo#3]
Adjunto la siguiente bibliografía  para definir los conceptos teóricos sobre   revisiones de código en la memoria
- Understanding the GitHub Flow · GitHub Guides. (s. f.). https://guides.github.com/introduction/flow/
- Ways to Make Code Reviews More Effective. (s. f.). Recuperado 4 de octubre de 2016, a partir de https://www.infoq.com/articles/effective-code-reviews?utm_source=infoqWeeklyNewsletter&utm_medium=WeeklyNL_EditorialContent_culture-methods&utm_campaign=10042016news
- A whole new Universe. (s. f.). Recuperado 4 de octubre de 2016, a partir de https://github.com/universe-2016
- Bernhart, M., & Grechenig, T. (2013). On the understanding of programs with continuous code reviews. En 2013 21st International Conference on Program Comprehension (ICPC) (pp. 192-198). https://doi.org/10.1109/ICPC.2013.6613847
  -Bosu, A., Greiler, M., & Bird, C. (2015). Characteristics of Useful Code Reviews: An Empirical Study at Microsoft. En 2015 IEEE/ACM 12th Working Conference on Mining Software Repositories (pp. 146-156). https://doi.org/10.1109/MSR.2015.21
  -Mining Review Repositories. (s. f.). Recuperado 4 de octubre de 2016, a partir de http://sdlab.naist.jp/reviewmining/

**Comment by mjuez** [comment]
No he podido terminar esta tarea dentro del segundo Sprint, aún quedan varios conceptos por definir. Se continuará en el siguiente Sprint.
