### ISSUE TITLE
Aprendizaje Gerrit Code Review

### ISSUE THREAD

**Issue by clopezno** [mjuez/TFM2016_Analisis-Visual-Revisiones-Codigo#4]
Comprensión del como se realizan revisiones de código mediante Gerrit Code Review
- Integración con repositorios GitHub
- Integración con gestores de Tareas de GitHub
- Conocer los datos estructurados de las revisiones de código
- Conocer el API de comunicación con Gerrit Code Review
- Búsqueda de repositorios con revisiones de código

Usar la siguiente documentación 
Gerrit Code Review - A Quick Introduction. (s. f.). Recuperado 4 de octubre de 2016, a partir de https://review.gerrithub.io/Documentation/intro-quick.html

La aplicación de estos conceptos en el TFM pueden transformarse en un futuro en una tarae

**Comment by mjuez** [comment]
He modificado el título, ya que GerritHub es una herramienta que ofrece gestionar las revisiones de código de repositorios Github mediante Gerrit Code Review, pero es posible utilizar Gerrit Code Review sin usar GerritHub, de hecho todos los repositorios que estoy encontrado tienen su propio Gerrit Code Review.

De momento he encontrado los siguientes repositorios que utilizan Gerrit:
### Google Source
- Android
  - https://android-review.googlesource.com/#/q/status:open
- Go lang
  - https://go-review.googlesource.com/#/q/status:open
- Chromium
  - https://chromium-review.googlesource.com/q/status:open
- GWT (Google Web Toolkit)
  - https://gwt-review.googlesource.com/#/q/status:open
- Bazel
  - https://bazel-review.googlesource.com/#/q/status:open
- Dart
  - https://dart-review.googlesource.com/q/status:open (Muy poco uso)
### Otros
- Lineage OS (antiguo Cyanogen OS)
  - https://review.lineageos.org/#/q/status:open
- Asterisk
  - https://gerrit.asterisk.org/#/q/status:open
- Gerrithub
  - https://review.gerrithub.io/#/q/status:open
- AOKP (Android Open Kang Project)
  - http://gerrit.aokp.co/#/q/status:open
- OpenStack
  - https://review.openstack.org/#/q/status:open
- Eclipse
  - https://git.eclipse.org/r/#/q/status:open
- Wikimedia
  - https://gerrit.wikimedia.org/r/#/q/status:open
- OpenContrail
  - https://review.opencontrail.org/#/q/status:open
- RDOProject
  - https://review.rdoproject.org/r/#/q/status:open
- Linux Foundation
  - https://gerrit.linuxfoundation.org/infra/#/q/status:open
- Automotive Linux
  - https://gerrit.automotivelinux.org/gerrit/#/q/status:open
- Open Daylight
  - https://git.opendaylight.org/gerrit/#/q/status:open
- FD.io
  - https://gerrit.fd.io/r/#/q/status:open

Iré actualizando la lista a medida que vaya encontrando nuevos repositorios que utilicen Gerrit.

**Comment by mjuez** [comment]
También he estado estudiando alternativas a Gerrit Code Review. Encontré la siguiente lista:
 - https://en.wikipedia.org/wiki/List_of_tools_for_code_review

### ReviewBoard
La única de las alternativas que es similar es ReviewBoard (https://www.reviewboard.org/) aunque es mucho menos utilizada, he visto casos (como Asterisk) que utilizaban ReviewBoard y decidieron cambiar a Gerrit Code Review. Aun así encontré dos casos de organizaciones bastante conocidas que utilizan esta herramienta:
- Apache
  - https://reviews.apache.org/r/
- Cloudera
  - https://review.cloudera.org/r/

### Github (Pull Requests)
Github a través de Pull Request ofrece la posibilidad de realizar revisiones de código, también existe la figura del revisor, incluso al igual que en Gerrit, he visto revisiones automáticas hechas por robots.
Sin embargo, aquí me está costando más encontrar repositorios que hagan uso de las revisiones y puedan ser útiles. Me estoy guiando un poco por el filtro de Pull Request "Review Required".
Esto es lo que he encontrado hasta ahora:

- Google WebFundamentals
  - https://github.com/google/WebFundamentals
- Leaflet
  - https://github.com/Leaflet/Leaflet
- Plottable
  - https://github.com/palantir/plottable
- Eslint
  - https://github.com/eslint/eslint
- Roslyn
  - https://github.com/dotnet/roslyn
- Python
  - https://github.com/python/cpython (este tiene pocas revisiones)

Los siguientes repositorios cuentan con revisiones aprobadas, pero no utilizan la etiqueta Review Required, aun así he visto que hay comentarios por parte de revisores en líneas de código, supongo que podrían servirnos.
- Dotnet Corefx
  - https://github.com/dotnet/corefx
- Microsoft TypeScript
  - https://github.com/Microsoft/TypeScrip
- ElasticSearch
  - https://github.com/elastic/elasticsearch
- Rust
  - https://github.com/rust-lang/rust (pocas revisiones)
- Apple Swift
  - https://github.com/apple/swift (pocas revisiones)
- PowerShell
  - https://github.com/PowerShell/PowerShell (pocas revisiones)

**Comment by mjuez** [comment]
Tras estudiar las diferentes herramientas que hacen posible el uso de revisiones de código, hemos decidido trabajar con Github porque ha añadido esta funcionalidad a las "Pull Request" y creemos que se va a utilizar cada vez más debido a que actualmente Github es el líder de los repositorios de código.

**Comment by clopezno** [comment]
Pongo en contacto a @diegoguemes como revisor de la validez de los code review para experimentar con multilabel.
