### ISSUE TITLE
Identificar y definir gráficas que ayuden a interpretar las revisones de código 

### ISSUE THREAD

**Issue by clopezno** [mjuez/TFM2016_Analisis-Visual-Revisiones-Codigo#5]
Análizar el concepto de **revisión de código** extrayendo el diagrama conceptual para definir gráficas que ayuden a analizar el proceso de revisión de código en un proyecto.

![conceptualmodelcodereview](https://cloud.githubusercontent.com/assets/1453744/19074190/56d19d4c-8a3f-11e6-84da-6a8eec299d6c.png)
- Red de participantes en las revisiones (ver ejemplos en http://som-research.uoc.edu/tools/gila/)
- Análisis de revisiones de un usuario concreto
- Review time line (ver ejemplos en http://som-research.uoc.edu/tools/gila/)
- Text review analysis (tag cloud)
  -...

Usar ejemplos de de componentes gráficos de la biblioteca que se vaya a utilizar para implementación. Lo dejo a elección de Mario.
- D3.js (https://github.com/d3/d3/wiki/Gallery)
- Vaddin (http://demo.vaadin.com/sampler/#ui)

**Comment by mjuez** [comment]
Una de las mejoras a incluir en #19, es añadir los conceptos teóricos de este diagrama, como comentamos en la pasada reunión, la parte importante del diagrama es la entidad "Review", no Revision y Version, ya que se refieren al cambio en sí, además estas dos entidades al parecer no existen en GIT, si no que son típicas de subversion ([véase esta pregunta en stackoverflow](http://stackoverflow.com/questions/4120001/what-is-the-git-equivalent-for-revision-number)), en GIT se podría decir que versión y revisión del cambio son lo mismo, y es el identificador del commit.

Estoy de acuerdo con incluir el diagrama en la parte de conceptos teóricos, pero creo que debe ser un diagrama adaptado a lo que tenemos en git, mi propuesta es la siguiente:


![nuevo diagrama](https://lh5.googleusercontent.com/O5HkS3vDyUxYqY2IC952sr4dQnLbW15iVM4Yx-eB1YEZFx1rlXrJi-oCFR-lCdfyJYYHjygLdBbjU28=w1920-h907)

**Comment by clopezno** [comment]
No puedo ver el contenido del enlace al nuevo diagrama pero estoy totalmente de acuerdo con tu razonamiento.

**Comment by mjuez** [comment]
Se había roto el enlace a la imagen del diagrama, ahora parece que ya se vuelve a ver.

**Comment by clopezno** [comment]
Perdona Mario he contestado en  #19.

**Comment by mjuez** [comment]
Ya he hecho los cambios, creo que podemos dar por cerrada esta issue.
