### ISSUE TITLE
Estudio de servidor de despliegue de aplicaciones Web

### ISSUE THREAD

**Issue by clopezno** [mjuez/TFM2016_Analisis-Visual-Revisiones-Codigo#6]
Lectura de la documentación de OpenShift con el fin de entender el funcionamiento de la plataforma y como poder desplegar una instancia de SonarQube.

Como fuente principal sugiero la información disponible en los siguientes enlaces:
    -[Guía del desarrollador de OpenShift] https://developers.openshift.com/en/overview-what-is-openshift.html
   -[Guía del usuario de OpenShift Origin] https://docs.openshift.org/origin-m4/oo_user_guide.html

**Comment by mjuez** [comment]
Cree una cuenta en OpenShift y me han concedido acceso para su servicio NexGen WebConsole. He estado mirando un poco la documentación de la herramienta y entiendo que el despliegue de las aplicaciones funciona a través de los cambios realizados en Github.
Para integrar Openshift con el proyecto he estado mirando la herramienta de integración continua [Travis CI](https://github.com/integrations/travis-ci), que permite trabajar con Openshift y además también posibilita la automatización de la ejecución de los test.

Por el momento creo que no se puede cerrar esta issue en este sprint ya que aún no he conseguido desplegar ninguna aplicación de prueba en Openshift.
