### ISSUE TITLE
Exportar revisiones de un repositorio en formato CSV

### ISSUE THREAD

**Issue by mjuez** [mjuez/TFM2016_Analisis-Visual-Revisiones-Codigo#69]
La última funcionalidad a añadir es la exportación de todas las revisiones de un repositorio en formato CSV para facilitar su uso externo, por ejemplo, en tareas de minería de datos.
Cada fila del fichero CSV se debe corresponder con una revisión y tener el siguiente formato:

```csv
id revisión, id repositorio, login creador repositorio, nombre repositorio, lenguaje, fecha de creación repositorio, fecha de actualización repositorio, id pull request, título pull request, cuerpo pull request, estado de revisión, cuerpo revisión, login revisor
```

La descarga del CSV se debe poder hacer dede un botón adicional en la vista de un repositorio.

**Comment by mjuez** [comment]
He añadido un botón a la vista de un repositorio para descargar el fichero CSV.
Un ejemplo de CSV se puede descargar desde [aquí](http://anvireco-dev.herokuapp.com/api/repo/elastic/elasticsearch/csv).
@clopezno, puedes descargarlo para ver si te sirve para las tareas de minería o necesitas algun campo más u otro formato diferente.

**Comment by clopezno** [comment]
El formato me parece correcto, lo he exportado con LibreOffice y lo ha reconociddo.
Si que me gustaría disponer de algun dato más de la PullRequest al final del fichero csv. En concreto de estos

```
state: string,
locked: boolean,
created_at: Date,
updated_at: Date,
closed_at: Date,
merged: boolean,
mergeable: boolean,
comments: number,
reviews: number,
review_comments: number,
commits: number,
additions: number,
deletions: number,
changed_files: number
```
